config/routes.rb
Rails.application.routes.draw do
	root "posts#index"

	get "/posts" => "posts#index", as: "posts"
	get "/post/:id" => "posts#show", as: "post"

	namespace :admin do
		resources :posts, path_names: { show: "preview" }
		resources :settings, only: [:edit, :update, :index]
		resources :users

		get "/" => :index

		scope :controller => :sessions do
			get "login" => :new
			post "login" => :create
			get "logout" => :destroy
		end
	end
end

app/models/post.rb
class Post < ApplicationRecord
	has_one :seo_data,
			:as => :page,
			:dependent => :destroy

	accepts_nested_attributes_for :seo_data
end

app/controllers/admin/dashboard/posts_controller.rb
class Admin::Dashboard::PostsController < AdminController
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /admin/dashboard/posts
  def index
    @posts = Post.all
  end

  # GET /admin/dashboard/posts/1
  def show
  end

   # GET /admin/dashboard/posts/new
  def new
    @post = Post.new
    #set_h1 "Create a New Post"
  end

  # GET /admin/dashboard/posts/1/edit
  def edit
    #set_h1 "Edit a Post"
  end

  # POST /admin/dashboard/posts
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /admin/dashboard/posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /admin/dashboard/posts/1
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

   private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :content, seo_data_attributes: [:meta_title, :meta_description, :meta_robots])
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :get_posts, only: [:show, :index, :edit]

  # GET /admin/dashboard/posts
  def index
  end

  # GET /admin/dashboard/posts/1
  def show
  end

   # GET /admin/dashboard/posts/new
  def new
    @post = Post.new
    #set_h1 "Create a New Post"
  end

  # GET /admin/dashboard/posts/1/edit
  def edit
    #set_h1 "Edit a Post"
  end

  # POST /admin/dashboard/posts
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_post_url(@post), notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /admin/dashboard/posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to admin_post_url(@post), notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /admin/dashboard/posts/1
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

   private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def get_posts
      @posts = Post.all.order(:created_at => :desc)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :content, seo_data_attributes: [:meta_title, :meta_description, :meta_robots, :seo_h1])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  # GET /posts
  def index
    @posts = Post.all.order(:created_at => :desc)
    set_h1 "Web Developement Blog"
  end

  # GET /posts/1
  def show
    if @post.seo_data.meta_title.empty?
      set_title @post.name
    else
      set_title @post.seo_data.meta_title
    end

    set_h1 @post.name # To do: Create H1 field in SEO Table
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :content, seo_data_attributes: [:meta_title, :meta_description, :meta_robots, :seo_h1])
    end
end

app/helpers/admin/dashboard/posts_helper.rb
module Admin::Dashboard::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.erb
<%= form_for @post, url: admin_posts_path do |posts_form| %>
	<%= posts_form.label :name %><br/>
	<%= posts_form.text_field :name %><br/>
	<%= posts_form.label :content %><br/>
	<%= posts_form.text_area :content, rows: 15 %><br />

	<%= posts_form.fields_for :seo_data_attributes, @post.seo_data do |seo_data_fields| %>
		<%= seo_data_fields.label :meta_title %><br/>
		<%= seo_data_fields.text_field :meta_title %><br/>
		<%= seo_data_fields.label :seo_h1 %><br/>
		<%= seo_data_fields.text_field :seo_h1 %><br/>
		<%= seo_data_fields.label :meta_description %><br/>
		<%= seo_data_fields.text_area :meta_description, rows: 3 %><br/>
		<%= seo_data_fields.label :meta_robots %><br/>
		<%= seo_data_fields.text_field :meta_robots %><br/>
	<% end %>

	<%= posts_form.submit %>
<% end %>

app/views/admin/posts/_list_posts.erb
<ul class="item-list">
	<% @posts.each do |post| %>
		<li class="item">
			<%= link_to admin_post_url(post) do %>
				<div class="item-header">
					<p class="item-header-subtitle">Charles Hollenbeck</p>
					<p class="item-header-title"><%= post.name %></p>
				</div>
				<div class="item-content">
					Created <%= time_ago_in_words(post.created_at) %> ago
				</div>
			<% end %>
		</li>
	<% end %>
</ul>

app/views/admin/posts/edit.erb
<%= render partial: "list_posts" %>
<div class="content-wrapper">
	<div class="content">
		<%= render partial: "form" %>
	</div>
</div>

app/views/admin/posts/index.erb
<% if @posts.length > 0 %>
	<%= render partial: "list_posts" %>
<% else %>
	<p>No Posts to Show</p>
<% end %>

app/views/admin/posts/new.erb
<div class="content-wrapper">
	<div class="content">
		<%= render partial: "form" %>
	</div>
</div>

app/views/admin/posts/show.erb
<%= render partial: "list_posts" %>

<div class="content-wrapper">
	<header>
		<h1><%= @post.name %></h1>
		<ul class="action-buttons">
			<li><%= link_to "Edit",  edit_admin_post_url(@post), class: "edit-button" %></li>
			<li><%= link_to "Delete",  admin_post_url(@post), :method => :delete, class: "destroy-button", data: { confirm: 'Are you sure?' } %></li>
		</ul>
	</header>
	<div class="content">
		<% if @post.seo_data.seo_h1 %>
			<h1><%= @post.seo_data.seo_h1 %></h1>
		<% end %>
		<%= markdown(@post.content) %>
	</div>
</div>