config/routes.rb
Rails.application.routes.draw do
	root "posts#index"

	get "/posts" => "posts#index", as: "posts"
	get "/post/:id" => "posts#show", as: "post"

	namespace :admin do
		resources :posts, path_names: { show: "preview" }
		resources :settings, only: [:edit, :update, :index]
		resources :users

		get "/" => :index

		scope :controller => :sessions do
			get "login" => :new
			post "login" => :create
			get "logout" => :destroy
		end
	end
end

app/models/setting.rb
class Setting < ApplicationRecord
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < AdminController
  layout "admin_login"
  before_action :set_setting, only: [:edit, :update]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1/edit
  def edit
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to admin_settings_path, notice: 'Setting was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:value)
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/1/edit
  def edit
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:name, :value)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/admin/settings/_form.erb
<%= form_for @setting, url: admin_setting_path do |f| %>
  <div class="field">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/settings/edit.erb
<div class="content-wrapper">
	<div class="content">
		<header>
			<h1>Editing Setting: <%= @setting.name %></h1>
		</header>

		<%= render partial: 'form' %>
	</div>
</div>

app/views/admin/settings/index.erb
<div class="content-wrapper">
  <div class="content">
    <h1>Settings</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Value</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @settings.each do |setting| %>
          <tr>
            <td><%= setting.name %></td>
            <td><%= setting.value %></td>
            <td><%= link_to 'Edit', edit_admin_setting_url(setting) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>