config/routes.rb
Rails.application.routes.draw do
	root "posts#index"

	get "/posts" => "posts#index", as: "posts"
	get "/post/:id" => "posts#show", as: "post"

	namespace :admin do
		resources :posts, path_names: { show: "preview" }
		resources :settings, only: [:edit, :update, :index]
		resources :users

		get "/" => :index

		scope :controller => :sessions do
			get "login" => :new
			post "login" => :create
			get "logout" => :destroy
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :get_users, only: [:show, :index, :edit]

  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_url(@user), notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /admin/dashboard/posts/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_url(@user), notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /admin/dashboard/posts/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
    end
  end

   private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def get_users
      @users = User.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/_form.erb
<%= form_for @user, url: admin_user_path do |f| %>
	<%= f.label :name %><br />
	<%= f.text_field :name %> <br/>
	<%= f.label :email %><br />
	<%= f.text_field :email %> <br/>
	<%= f.label :password %><br />
	<%= f.password_field :password %> <br/>
	<%= f.label :password_confirmation %><br />
	<%= f.password_field :password_confirmation %> <br/>
	<%= f.submit %>
<% end %>

app/views/admin/users/_list_users.erb
<ul class="item-list">
	<% @users.each do |user| %>
		<li class="item">
			<%= link_to admin_user_url(user) do %>
				<div class="item-header"><!-- Add Role Here Later
					<p class="item-header-subtitle">Charles Hollenbeck</p> -->
					<p class="item-header-title"><%= user.name %></p>
				</div>
				<div class="item-content">
					Created <%= time_ago_in_words(user.created_at) %> ago
				</div>
			<% end %>
		</li>
	<% end %>
</ul>

app/views/admin/users/edit.erb
<%= render partial: "list_users" %>
<div class="content-wrapper">
	<div class="content">
		<%= render partial: "form" %>
	</div>
</div>

app/views/admin/users/index.erb
<% if @users.length > 0 %>
	<%= render partial: "list_users" %>
<% else %>
	<p>No Users to Show</p>
<% end %>

app/views/admin/users/new.erb
<div class="content-wrapper">
	<div class="content">
		<%= render partial: "form" %>
	</div>
</div>

app/views/admin/users/show.erb
<%= render partial: "list_users" %>

<div class="content-wrapper">
	<header>
		<h1>Viewing User: <%= @user.name %></h1>
		<ul class="action-buttons">
			<li><%= link_to "Edit",  edit_admin_user_url(@user), class: "edit-button" %></li>
			<li><%= link_to "Delete",  admin_user_url(@user), :method => :delete, class: "destroy-button", data: { confirm: 'Are you sure?' } %></li>
		</ul>
	</header>

	<div class="content">
		<ul>
			<li><strong>E-mail:</strong> <%= @user.email %></li>
		</ul>
	</div>
</div>