config/routes.rb
Rails.application.routes.draw do
	root "posts#index"

	get "/posts" => "posts#index", as: "posts"
	get "/post/:id" => "posts#show", as: "post"

	namespace :admin do
		resources :posts, path_names: { show: "preview" }
		resources :settings, only: [:edit, :update, :index]
		resources :users

		get "/" => :index

		scope :controller => :sessions do
			get "login" => :new
			post "login" => :create
			get "logout" => :destroy
		end
	end
end

app/views/layouts/admin.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<title><%= @seo_meta_title %> | Charles Hollenbeck</title>
		<meta charset="UTF-8" />
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		<div id="wrapper">
			<nav>
				<ul>
					<li><%= link_to "Dashboard", admin_path, class: "pure-menu-link" %></li>
					<li>
						<%= link_to "Posts", admin_posts_path, class: "pure-menu-link " %>
						<ul>
							<li><%= link_to "View All", admin_posts_path, class: "pure-menu-link" %></li>
							<li><%= link_to "New", new_admin_post_path, class: "pure-menu-link" %></li>
						</ul>
					</li>
					<li>
						<%= link_to "Settings", admin_settings_path, class: "pure-menu-link " %>
					</li>
					<li>
						<%= link_to "Users", admin_users_path, class: "pure-menu-link " %>
						<ul>
							<li><%= link_to "View All", admin_users_path, class: "pure-menu-link" %></li>
							<li><%= link_to "New", new_admin_user_path, class: "pure-menu-link" %></li>
						</ul>
					</li>
				</ul>
			</nav>
			<main>
				<%= yield %>
			</main>
		</div>
	</body>
</html>

app/views/layouts/admin_login.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Login | Charles Hollenbeck</title>
		<meta charset="UTF-8" />
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="wrapper">
			<main>
				<%= yield %>
			</main>
		</div>
	</body>
</html>

app/views/layouts/application.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<title><%= @seo_meta_title %> | Charles Hollenbeck</title>
		<meta name="description" content="<%= @seo_meta_description %>" />
		<meta name="robots" content="<%= @seo_meta_robots %>" />
		<meta charset="UTF-8" />
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		<nav>
			<ul>
				<li><%= link_to "Home", :root %></li>
				<li><%= link_to "Blog", :posts %></li>
			</ul>
		</nav>
		<div id="wrapper">
			<main>
				<div class="header">
					<h1><%= @seo_h1 %></h1>
				</div>
				<div id="content">
					<%= yield %>
				</div>
			</main>
			<aside>
				<p class="heading">Latest Github Updates</p>
				<div class="github">
					<% recent_github_updates.each do |repo| %>
					<div class="repo">
						<%= link_to repo[:html_url] do %>
						<p class="repo-name"><%= repo[:name] %></p>
						<p class="repo-last-pushed">Updated <%= time_ago_in_words (repo[:pushed_at]) %> ago</p>
						<% end %>
					</div>
					<% end %>
				</div>
			</aside>
		</div>
		<footer>
			&copy; <%= Time.now.year %> Charles Hollenbeck
		</footer>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<title><%= @seo_meta_title %> | Charles Hollenbeck</title>
		<meta name="description" content="<%= @seo_meta_description %>" />
		<meta name="robots" content="<%= @seo_meta_robots %>" />
		<meta charset="UTF-8" />
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		<nav>
			<ul>
				<li><%= link_to "Home", :root %></li>
				<li><%= link_to "Blog", :posts %></li>
			</ul>
		</nav>
		<div id="wrapper">
			<main>
				<div class="header">
					<h1><%= @seo_h1 %></h1>
				</div>
				<div id="content">
					<%= yield %>
				</div>
			</main>
			<aside>
				<p class="heading">Latest Github Updates</p>
				<div class="github">
					<% recent_github_updates.each do |repo| %>
					<div class="repo">
						<%= link_to repo[:html_url] do %>
						<p class="repo-name"><%= repo[:name] %></p>
						<p class="repo-last-pushed">Updated <%= time_ago_in_words (repo[:pushed_at]) %> ago</p>
						<% end %>
					</div>
					<% end %>
				</div>
			</aside>
		</div>
		<footer>
			&copy; <%= Time.now.year %> Charles Hollenbeck
		</footer>
	</body>
</html>